# Generated by Django 5.0.6 on 2025-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopingaddress',
            old_name='address',
            new_name='shoping_address',
        ),
        migrations.RenameField(
            model_name='shopingaddress',
            old_name='city',
            new_name='shoping_city',
        ),
        migrations.RenameField(
            model_name='shopingaddress',
            old_name='country',
            new_name='shoping_country',
        ),
        migrations.RenameField(
            model_name='shopingaddress',
            old_name='full_name',
            new_name='shoping_full_name',
        ),
        migrations.RenameField(
            model_name='shopingaddress',
            old_name='old_cart',
            new_name='shoping_old_cart',
        ),
        migrations.RenameField(
            model_name='shopingaddress',
            old_name='phone_number',
            new_name='shoping_phone_number',
        ),
        migrations.RenameField(
            model_name='shopingaddress',
            old_name='state',
            new_name='shoping_state',
        ),
        migrations.RemoveField(
            model_name='shopingaddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shopingaddress',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='shopingaddress',
            name='shoping_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shopingaddress',
            name='shoping_zip_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
