# Generated by Django 5.0.6 on 2024-05-12 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_is_sale_products_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
